# Generated by Django 5.1.2 on 2024-10-18 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0004_remove_image_image_file_image_image_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
